version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:14.16.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.2
jobs:
  build:
    executor: node
    working_directory: ~/znk-whatsapp-notifications-worker

    steps:
      - checkout:
          path: ~/znk-whatsapp-notifications-worker

      # Restore local dependencies from cache
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-

      # Install dependencies
      - run:
          name: Install local dependencies
          command: yarn install

      # Cache local dependencies
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
     # Save Cache
      - save_cache:
          key: znk-whatsapp-notifications-worker-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - utils
            - processors
            - .env
            - package.json
            - .ebextensions
            - index.js
  deploy-server:
    parameters:
      application_name:
        type: string
      environment_name:
        type: string
        default: production
    docker:
      - image: 'cimg/base:stable'
    working_directory: ~/znk-whatsapp-notifications-worker

    steps:
      - attach_workspace:
          at: ~/znk-whatsapp-notifications-worker
      # Restore project cache
      - restore_cache:
          key: znk-whatsapp-notifications-worker-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      # Restore dependencies cache
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Check project folder
          command: ls
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      # Install AWS EB CLI
      - eb/setup
      # Deploy to EB
      - deploy:
          name: Deploy to EB
          command: |
            eb init "<< parameters.application_name >>" -r ${AWS_REGION} -p "node.js"
            eb use "<< parameters.environment_name >>"
            eb deploy

workflows:
  version: 2

  # Workflows defined for each package.
  server:
    jobs:
      - build:
          name: server-build
          filters:
            branches:
              only:
                - master
                - dev
      - deploy-server:
          name: server-deploy-dev
          application_name: whatsapp-notifications-worker
          environment_name: whatsapp-notifications-worker-dev-1
          filters:
            branches:
              only:
                - dev
          requires:
            - server-build
      - deploy-server:
          name: server-deploy-prod
          application_name: znk-api-v2
          environment_name: notificationsWorker
          filters:
            branches:
              only:
                - dev
          requires:
            - server-build
